name: Deployment

on:
  push:
    branches:
      - deploy

jobs:
  access-droplet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into DigitalOcean droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: root
          key: ${{ secrets.CD }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /var/www/fitZen_by_Intellecta/
            git remote set-url origin https://dnadawa:${{ secrets.TOKEN }}@github.com/DevmalWije/fitZen_by_Intellecta.git
            git stash
            git pull
            pm2 stop app
            pm2 start app
