name: Deployment

on:
  push:
    branches:
      - deploy

jobs:
  access-droplet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into DigitalOcean droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: root
        #   key: ${{ secrets.CD }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22
          script: |
            # Your SSH commands go here
            echo "Hello, Droplet!"
